# Generated by Django 4.0.4 on 2022-05-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone/Celular')),
                ('email', models.EmailField(max_length=80, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Fornecedor',
            },
        ),
    ]
