# Generated by Django 4.0.4 on 2022-05-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servico', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoModel',
            new_name='ServicoModel',
        ),
        migrations.AlterModelOptions(
            name='servicomodel',
            options={'verbose_name': 'Serviço'},
        ),
    ]
