# Generated by Django 4.0.4 on 2022-05-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('fornecedor', models.CharField(max_length=30, verbose_name='Fornecedor')),
                ('peso_liq', models.IntegerField(max_length=6, verbose_name='Peso líquido (g)')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço de venda')),
                ('estoque_min', models.IntegerField(max_length=4, verbose_name='Estoque mínimo')),
            ],
        ),
    ]
