# Generated by Django 4.0.4 on 2022-05-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='estoque_min',
            field=models.IntegerField(verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='produtomodel',
            name='peso_liq',
            field=models.IntegerField(verbose_name='Peso líquido (g)'),
        ),
    ]
