# Generated by Django 4.0.4 on 2022-05-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0002_alter_produtomodel_estoque_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtomodel',
            options={'verbose_name': 'Produto'},
        ),
    ]
