# Generated by Django 4.0.4 on 2022-05-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone/Celular')),
                ('email', models.EmailField(max_length=80, verbose_name='E-mail')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('is_colaborador', models.BooleanField(verbose_name='É colaborador?')),
            ],
        ),
    ]
