# Generated by Django 4.0.4 on 2022-05-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoamodel',
            options={'verbose_name': 'Pessoa'},
        ),
    ]
